version: '3.8'

services:
  mobix-api:
    build:
      context: ./backend/Mobix.Api
      dockerfile: Dockerfile
    container_name: mobix_api
    restart: always
    ports:
      - "5152:8080"
    environment:
      ConnectionStrings__DefaultConnection: Host=dpg-d48a4d3ipnbc73dc9ea0-a.frankfurt-postgres.render.com;Port=5432;Database=mobix_db;Username=mobix_db_user;Password=wKZ3PUeuUAiZuTbhoPQwHW9tSxlbbRTx

      Jwt__Key: M0bixIsSuperS3cretKey!77@wE$qK&zP*tY#v9
      Jwt__Issuer: MobixApi
      Jwt__Audience: MobixApiClient
      ASPNETCORE_URLS: http://+:8080
    volumes:
      - ./backend/Mobix.Api/publish:/app:ro
  
  mobix-frontend:
    image: nginx:alpine
    container_name: mobix_frontend
    restart: always
    ports:
      - "80:80" 
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - mobix-api